### ISSUE TITLE
[ TRON ] Remove pending transaction

### ISSUE THREAD

**Issue by leoneparise** [trustwallet/platform#131]
There is no pending transaction for Tron, as we have for cosmos. Freezing balance is not a pending transaction.

![Simulator Screen Shot - iPhone X - 2019-09-23 at 01 05 25](https://user-images.githubusercontent.com/1442927/65401523-09796500-dd9f-11e9-8070-2ae861f02cab.png)

**Comment by dpereskokov** [comment]
@leoneparise renaming to frozen fo Tron will solve an issue. What do you think?

**Comment by leoneparise** [comment]
It wont. The value will stay frozen even if staked. We should remove it

**Comment by leoneparise** [comment]
Fixed in master.
